### ISSUE TITLE
Does not run in Windows

### ISSUE THREAD

**Issue by Alex20204** [citronneur/rdpy#106]
Hi, Error in windows:

Traceback (most recent call last):
  File "C:\Python27\Scripts\rdpy-rdpclient.py", line 27, in <module>
    from rdpy.ui.qt4 import RDPClientQt
  File "C:\Python27\lib\site-packages\rdpy\ui\qt4.py", line 33, in <module>
    import rle
ImportError: DLL load failed: The specified module could not be found.

**Comment by citronneur** [comment]
You need to install bre built binaries (https://files.pythonhosted.org/packages/0c/19/1175d3c6d320dc0b49ee33b08b5e0537665d19d6e87b3b910c287d0ee45e/rdpy-1.3.2.win-amd64-py2.7.exe) or Microsoft Visual Studio.
Have a nice day!
