### ISSUE TITLE
rdpy.core.error.InvalidExpectedDataException in rdpy-rdpmitm.py

### ISSUE THREAD

**Issue by adepasquale** [citronneur/rdpy#15]
I have tried rdpy-rdpmitm.py connecting to a target Win7 machine. If I use rdpy-rdpclient.py it works like a charm, but if I try with `rdesktop` here's what happens. Still haven't tried with Microsoft's Terminal Services client `mstsc`.

```
% ./rdpy-rdpmitm.py -o /tmp 192.168.56.3
ERROR : Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
Unhandled Error
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "venv/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 209, in dataReceived
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/tpkt.py", line 195, in readData
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 146, in recvData
    
  File "build/bdist.linux-x86_64/egg/rdpy/core/type.py", line 897, in readType
    
  File "build/bdist.linux-x86_64/egg/rdpy/core/type.py", line 97, in read
    
  File "build/bdist.linux-x86_64/egg/rdpy/core/type.py", line 477, in __read__
    
rdpy.core.error.InvalidExpectedDataException: <class 'rdpy.core.type.UInt8'> const value expected 240 != 128

```

**Comment by citronneur** [comment]
Sorry after investigation is a rdesktop bugs. But the project is not maintain. I try a push request on https://github.com/eby/rdesktop. Prefer to use FreeRDP.
