### ISSUE TITLE
Unhandled Error Nego fail

### ISSUE THREAD

**Issue by ex0dus-cpp** [citronneur/rdpy#36]
```
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 88, in callWi
thLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 73, in callWi
thContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in c
allWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in ca
llWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\qtreactor\qt4base.py", line 100, in _read
    data = w.doRead()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 209, in doR
ead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 215, in _da
taReceived
    rval = self.protocol.dataReceived(data)
  File "build\bdist.win32\egg\rdpy\protocol\rdp\nla\cssp.py", line 208, in dataR
eceived

  File "build\bdist.win32\egg\rdpy\core\layer.py", line 209, in dataReceived

  File "build\bdist.win32\egg\rdpy\protocol\rdp\tpkt.py", line 195, in readData

  File "build\bdist.win32\egg\rdpy\protocol\rdp\x224.py", line 199, in recvConne
ctionConfirm

rdpy.core.error.RDPSecurityNegoFail: negotiation failure code 2
```
Hello, why this error is unhandled? Can I catch it (so it is not displayed in the console) so as not to disrupt the logic of the program?

**Comment by ex0dus-cpp** [comment]
Ok, sorry to trouble, i catched it in file
C:\Python27\Lib\site-packages\twisted\internet\selectreactor.py on line 152 `#log.err()`
