### ISSUE TITLE
Various syntax errors for all Python scripts

### ISSUE THREAD

**Issue by crasslr** [citronneur/rdpy#44]
I know there's a high chance that this is my fault, but I can't get anything to work. I'm running Arch Linux and installed all dependencies using PIP as suggested. Here's all the errors I'm getting:

```
$ rdpy-rdpclient.py
  File "/usr/bin/rdpy-rdpclient.py", line 225
    """
      ^
SyntaxError: invalid syntax
```

```
$ rdpy-rdphoneypot.py
  File "/usr/bin/rdpy-rdphoneypot.py", line 153
    """
      ^
SyntaxError: invalid syntax
```

```
$ rdpy-rdpmitm.py
  File "/usr/bin/rdpy-rdpmitm.py", line 267
    """
      ^
SyntaxError: invalid syntax
```

```
$ rdpy-rdpscreenshot.py
  File "/usr/bin/rdpy-rdpscreenshot.py", line 191
    print "Usage: rdpy-rdpscreenshot [options] ip[:port]"
                                                        ^
SyntaxError: Missing parentheses in call to 'print'
```

```
$ rdpy-rssplayer.py
  File "/usr/bin/rdpy-rssplayer.py", line 73
    print "Usage: rdpy-rssplayer [-h] rss_filepath"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
```

```
$ rdpy-vncclient.py
Traceback (most recent call last):
  File "/usr/bin/rdpy-vncclient.py", line 27, in <module>
    from rdpy.ui.qt4 import RFBClientQt
  File "/usr/lib/python3.5/site-packages/rdpy/ui/qt4.py", line 27, in <module>
    from rdpy.protocol.rfb.rfb import RFBClientObserver
  File "/usr/lib/python3.5/site-packages/rdpy/protocol/rfb/rfb.py", line 28, in <module>
    from rdpy.core.layer import RawLayer, RawLayerClientFactory
  File "/usr/lib/python3.5/site-packages/rdpy/core/layer.py", line 110, in <module>
    from type import Stream
ImportError: No module named 'type'
```

```
$ rdpy-vncscreenshot.py
  File "/usr/bin/rdpy-vncscreenshot.py", line 135
    print "Usage: rdpy-vncscreenshot [options] ip[:port]"
                                                        ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by citronneur** [comment]
I think you are using python3 but rdpy is only availebale on python 2 due to twisted. A project is to pass rdpy in python 3 and eventio
