### ISSUE TITLE
How to use rdpy-rdpmitm.py command?

### ISSUE THREAD

**Issue by bobolkevin** [citronneur/rdpy#50]
i use the commmand:
rdpy-rdpmitm.py -o c:/123 192.168.83.185
the result is:

Traceback (most recent call last):
  File "C:\Python27\Scripts\rdpy-rdpmitm.py", line 309, in <module>
    reactor.listenTCP(int(listen), ProxyServerFactory(parseIpPort(args[0]), oupu
tDirectory, privateKeyFilePath, certificateFilePath, clientSecurity))
  File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 478,
in listenTCP
    p.startListening()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 984, in sta
rtListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:3389: [Errno 10
048] Only one usage of each socket address (protocol/network address/port) is no
rmally permitted.

**Comment by dumbo0** [comment]
hi man, did u solved the problem??

**Comment by darryllane** [comment]
youve already got port 3389 listening. So your trying to listen on the port that is already listening
