### ISSUE TITLE
dpy-rdphoneypot.py is broken

### ISSUE THREAD

**Issue by itJunky** [citronneur/rdpy#55]
`$ rdpy-rdphoneypot.py                                                                                                                                         LA: 0.24 
[*] INFO:	Build size map
[*] INFO:	Connection from 127.0.0.1:48412
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 221, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 209, in dataReceived
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/tpkt.py", line 195, in readData
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 148, in recvData
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/t125/mcs.py", line 243, in recvData
    
  File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 102, in <lambda>
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/sec.py", line 470, in recv
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/pdu/layer.py", line 504, in recvClientFontListPDU
    
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 480, in onReady
    
  File "/usr/local/lib/python2.7/dist-packages/rdpy-1.3.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/rdpy-rdphoneypot.py", line 56, in onReady
    rssFilePath = sorted(self._rssFileSizeList, key = lambda x: abs(x[0][0] * x[0][1] - size))[0][1]
exceptions.IndexError: list index out of range
`

**Comment by Mahagon** [comment]
im getting the same error running the honey pot on ubuntu 16.04

**Comment by anirudhrata** [comment]
I think you'll have to pass the rss file as argument. There is no validation if an argument is passed or not.

**Comment by emilirgi18** [comment]
Does anyone have a fix on this?
