### ISSUE TITLE
How to creat Recorded Session Scenario for rdpy-rdphoneypot.py

### ISSUE THREAD

**Issue by dongshan3** [citronneur/rdpy#60]
Sir,

I tried to test on Windows 2008 32bit, but failed,

C:\Python27\Scripts>rdpy-rdphoneypot.py -l 3390
[*] INFO:       Build size map
[*] INFO:       Connection from 113.75.31.17:64084
[*] INFO:       Connection from 113.75.31.17:64087
Unhandled Error

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 103, in callW
ithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 86, in callWi
thContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 122, in c
allWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 85, in ca
llWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 1
49, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 208, in doR
ead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 214, in _da
taReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\rdpy\core\layer.py", line 209, in dataRece
ived
    self.recv(expectedData)
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\tpkt.py", line 195, in r
eadData
    self._presentation.recv(data)
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\x224.py", line 148, in r
ecvData
    self._presentation.recv(data)
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\t125\mcs.py", line 243,
in recvData
    self._channels[channelId].recv(data)
  File "C:\Python27\lib\site-packages\rdpy\core\layer.py", line 102, in <lambda>

    callback = lambda x:self.__class__.recv(self, x)
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\sec.py", line 470, in re
cv
    self._presentation.recv(data)
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\pdu\layer.py", line 504,
 in recvClientFontListPDU
    self._listener.onReady()
  File "C:\Python27\lib\site-packages\rdpy\protocol\rdp\rdp.py", line 480, in on
Ready
    observer.onReady()
  File "C:\Python27\Scripts\rdpy-rdphoneypot.py", line 56, in onReady
    rssFilePath = sorted(self._rssFileSizeList, key = lambda x: abs(x[0][0] * x[
0][1] - size))[0][1]
exceptions.IndexError: list index out of range

anirudhrata said that it need to pass the rss file as argument, but there is no rss file in the rdpy packages, and I tried to google, there is no example about RSS file too.

Thanks.

**Comment by tkeeler33** [comment]
Not sure if you are still looking for the answer, but you need to use the `rdpy-rdpmitm.py` command to record a session and create an `.rss` file. 

Hope this helps

**Comment by ner00** [comment]
Getting the error bellow:
> Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again.

Is this a common error/mistake?

Issue: https://github.com/citronneur/rdpy/issues/69
